name: Main
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: github -k repo -t ${{ secrets.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 }} https://github.com/SpectralOps/spectral-github-action --include-tags base,audit --ok
